### ISSUE TITLE
products not loading after upgrade scandipwa to 2.8.2

### ISSUE THREAD

**Issue by magentoguyspk** [scandipwa/performance#1]
Hi
Please check here: I have issue that products are not loading.
https://m2.outletpad.com/
the error is this one:   http://prntscr.com/qqqplo
**Uncaught Error: Cannot instantiate interface Magento\InventoryApi\Api\SourceItemRepositoryInterface in /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116**

As we have disabled "Magento_InventoryApi" module ,as we dont want it
but in latest version of scandipwa in this module "ScandiPWA\Performance" 
interface is used in this file
vendor/scandipwa/performance/src/Model/Resolver/Products/DataPostProcessor/Stocks.php
http://prntscr.com/qqqr2n

so I am assuming that's why products are not loading due to this.
can you please let me know ,how this issue can be solved.?

**Comment by alfredsgenkins** [comment]
@eli-l what can be done? Add a dependency to this module - limits us a little? Maybe make a different implementation if module is there?
