### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by fooman** [scandipwa/performance#3]
This line here
https://github.com/scandipwa/performance/blob/master/src/etc/schema.graphqls#L12 leads to a dependency on https://github.com/scandipwa/catalog-graphql/blob/2.x/src/etc/schema.graphqls#L58

otherwise if both are not installed it will error with

```
1 exception(s):
Exception #0 (GraphQL\Error\Error): Type "AttributeWithValue" not found in document.
```

**Comment by alfredsgenkins** [comment]
I think that is fixes as of today: https://github.com/scandipwa/performance/blob/e705ec85dbbd7dd5f39cc6aaf79401a11ba2a7cf/src/etc/module.xml

Thanks for report!

**Comment by fooman** [comment]
@alfredsgenkins thanks for looking into this. The dependency is missing in the `composer.json` file as well. So if you just run `composer require scandipwa/performance` the above error will show up. Adding 

```
    "require": {
        "scandipwa/catalog-graphql": "^2.0"
    }
```
would do the trick.

Just to explain how I ran into this. I was looking for GraphQl review support. So I added `scandipwa/reviews-graphql` which requires this package but until the Catalog GraphQL is installed it will error.

Alternative solution would be to move 
https://github.com/scandipwa/catalog-graphql/blob/2.x/src/etc/schema.graphqls#L55-L74
into this package which would not impact catalog-graphql as it already has the dependency.

**Comment by fooman** [comment]
Just added https://github.com/scandipwa/performance/pull/7 for the above. If that works for you the following process would be my suggestion:

Merge PR and tag a new release for scandipwa/performance for example `1.0.5`. Then remove the definition from scandipwa/catalog-graphql and bump the required version of scandipwa/performance to 1.0.5 (happy to add another PR for that if you are happy with that approach).
