### ISSUE TITLE
Make product attributes usable on the PLP by setting 'Used in Product Listing' to Yes

### ISSUE THREAD

**Issue by joostm020** [scandipwa/performance#8]
**Description**:
I cannot use a product attribute on the PLP without having it visible on the PDP.

Currently you need both '**Used in Product Listing**' and '**Visible on Catalog Pages on Storefront**' set to **Yes**.
https://github.com/scandipwa/performance/blob/0734794545355fbda089fe8c5dbc8156fff7dcd2/src/Model/Resolver/Products/DataPostProcessor/Attributes.php#L297

**Expected behavior**:
Product attributes should be usable on the PLP by just setting '**Used in Product Listing**' to **Yes**.

**To Reproduce**:
1. Create a custom product attribute
2. Set 'is_visible_on_front' to No
3. Set 'used_in_product_listing' to Yes
4. Clear cache
5. Go to a category page to see if the attribute is present in the GraphQL response

**Versions**:
- ScandiPWA: latest

**Additional context**:
The attribute settings are a little bit confusing, because '**Visible on Catalog Pages on Storefront**' sounds like it's supposed for all pages, however the official documentation states it's really just for the product page.

**From the original docs:**

PROPERTY | DESCRIPTION
-- | --
Visible on Catalog Pages on Storefront | (Simple and virtual products only) To include the attribute on the Additional Information tab of the product page, select Yes. Options: Yes / No
Used in Product Listing | Depends on the theme. To include the attribute in product summaries that appear in catalog listings, select Yes.

https://docs.magento.com/user-guide/stores/attributes-product.html#storefront-properties

**Comment by alfredsgenkins** [comment]
Approved, merged.
